FROM node:16

ARG API_URI
ENV API_URI=${API_URI}
ENV PORT=3000
# Идентификатор счетчика Яндекс.Метрики.
ENV YM_ID=0

WORKDIR /home
COPY . /home
RUN sed "s|__API_URI__|\"${API_URI}\"|" src/globals.template.js > src/globals.js \
    && rm src/globals.template.js

RUN yarn install

VOLUME ["/home/build"]

ENTRYPOINT ["yarn", "start"]
