services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
      args:
        - API_URI=${API_URI}

