name: urfu-games
services:

  # Веб-клиент.
  frontend:
    container_name: urfu-games-frontend
    build: ./frontend
    environment:
      - API_URI=${API_URI}
      - FILES_URI=${FILES_URI}
      - PORT=${FRONTEND_PORT}
    volumes:
      - ./frontend:/root
    depends_on:
      - api
    ports:
      - 80:80

  # API сервис.
  api:
    container_name: urfu-games-api
    build: ./api
    environment:
      - API_URI=${API_URI}
      - FILES_URI=${FILES_URI}
      - DATABASE_URI=postgres://postgres:${POSTGRES_PASSWORD}@postgres:5432/main
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-Admin1234}
      - PORT=${API_PORT}
    volumes:
      - ./api:/root
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - ${API_PORT}:${API_PORT}

  # Сервис для загрузки файлов.
  files:
    container_name: urfu-games-files
    build: ./files
    environment:
      - API_URI=${API_URI}
      - FILES_URI=${FILES_URI}
      - PORT=${FILES_PORT}
    volumes:
      - ./files:/root
    ports:
      - ${FILES_PORT}:${FILES_PORT}

  # База данных PostgreSQL.
  postgres:
    container_name: urfu-games-postgres
    build: ./postgres
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

