services:
  frontend:
    container_name: frontend-urfu-games
    build: ./client
    environment:
      - HOST=${FRONTEND_HOSTNAME} # `FRONTEND_HOSTNAME` can be undefined
      - PORT=${FRONTEND_PORT}
      - API_URI=${API_URI}
    volumes:
      - ${PWD}/client/src:/root/src # code volume
    depends_on:
      - api
    network_mode: host

  api:
    container_name: api-urfu-games
    build: ./server
    environment:
      - API_URI=${API_URI}
      - DATABASE_URI=postgres://postgres:${POSTGRES_PASSWORD}@localhost:5432/main
      - PORT=${API_PORT}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-Admin1234}
    volumes:
      - ${PWD}/server/src:/root/src # code volume
    depends_on:
      postgres:
        condition: service_healthy
    network_mode: host

  postgres:
    container_name: postgres-urfu-games
    build: ./postgres
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    network_mode: host
