services:
  nginx:
    build: ./nginx
    ports:
      - 443:433
      - 80:80
    environment:
      - API_URI=${API_URI}
      - FILES_URI=${FILES_URI}
    depends_on:
      - client
      - api-service
      - progress-service
      - files-service
    volumes:
      - /var/www:/var/www

  client:
    build: .client
    environment:
      - API_URI=${API_URI}
      - YM_ID=${YM_ID:-0}
    depends_on:
      - api-service
      - progress-service
      - files-service
    volumes:
      - /var/www/urfugames.ru/html:/home/build
    profiles:
      - all

  api-service:
    build: ./server
    environment:
      - API_URI=${API_URI}
      - DATABASE_URI=postgres://postgres:${POSTGRES_PASSWORD}@postgres/main
    depends_on:
      postgres:
        condition: service_healthy

  files-service:
    build: ./files
    environment:
      - API_URI=${API_URI}
      - FILES_URI=${FILES_URI}
    volumes:
      - /var/www/files.urfugames.ru:/home/data

  progress-service:
    build: ./progress
    environment:
      - API_URI=${API_URI}
      - DATABASE_URI=postgres://postgres:${POSTGRES_PASSWORD}@postgres/progress
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    build: ./postgres
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
